logging:
  level:
    formation:
      conceptdev:
        facto:
          services: trace;
    root: info
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/factory
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      "[format_sql]": true
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username: factory.jee@gmail.com
    password: ofalldbahpqpdgis 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /factory
