logging:
  level:
    formation:
      conceptdev:
        facto:
          services: trace;
    root: info
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/factory
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      "[format_sql]": true
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
server:
  servlet:
    context-path: /factory
